#ifndef CONFIG_H
#define CONFIG_H

#define MAZE_SIZE 23

#define HUD_HEIGHT 2

#define MIN_PATH_LENGTH (MAZE_SIZE * MAZE_SIZE * 0.1)

#define PLAYER_MOVE_ANIMATION_DURATION 130
#define PLAYER_STATE_ANIMATION_DURATION PLAYER_MOVE_ANIMATION_DURATION * 2

#define LEVEL_INTERVAL 5

#define MIN_SPAWNER_COUNT 4

#define MAX_VISIBLE_RADIUS  (MAZE_SIZE / 2.0)
#define RADIUS_DECREASING_RATE 0.001

#endif
