#ifndef CONFIG_H
#define CONFIG_H

#define MAZE_SIZE         23
#define HUD_HEIGHT        2
#define MIN_PATH_LENGTH   (MAZE_SIZE * MAZE_SIZE * 0.1)

#define LEVEL_INTERVAL      5
#define MIN_SPAWNER_COUNT   4

#define CHARACTER_MOVE_ANIMATION_DURATION   150
#define CHARACTER_STATE_ANIMATION_DURATION  300

#define BASE_VISIBLE_RADIUS                 3.0
#define BASE_VISIBLE_RADIUS_MIN             1.0
#define BASE_VISIBLE_RADIUS_REDUCING_RATE   0.5
#define MAX_VISIBLE_RADIUS                  (MAZE_SIZE / 2.0)
#define RADIUS_REDUCING_RATE                0.001

#define ENEMY_MIN_STEPS   20
#define ENEMY_MAX_STEPS   30
#define ENEMY_SLOW_DOWN   1.1

#define ENEMY_SPAWN_INTERVEL                 3000
#define ENEMY_SPAWN_INTERVEL_MIN             100
#define ENEMY_SPAWN_INTERVEL_REDUCING_RATE   500

#define ENEMY_EXPLODE_RADIUS  8

#define SPOILED_DAMAGE  10.0

#define LEVEL_TRANSITION_DURATION   300
#define LEVEL_TRANSITION_REST       1000

#endif
