#ifndef CONFIG_H
#define CONFIG_H

#define MAZE_SIZE 23

#define HUD_HEIGHT 2

#define MIN_PATH_LENGTH (MAZE_SIZE * MAZE_SIZE * 0.1)

#define CHARACTER_MOVE_ANIMATION_DURATION 150
#define CHARACTER_STATE_ANIMATION_DURATION 300

#define LEVEL_INTERVAL 5

#define MIN_SPAWNER_COUNT 4

#define INITIAL_VISIBLE_RADIUS 104.0
#define MAX_VISIBLE_RADIUS  (MAZE_SIZE / 2.0)
#define RADIUS_DECREASING_RATE 0.001

#define ENEMY_MIN_STEPS 20
#define ENEMY_MAX_STEPS 30
#define ENEMY_SPAWN_INTERVEL 3000
#define ENEMY_SLOW_DOWN 1.1

#define ENEMY_EXPLODE_RADIUS 8

#define SPOILED_DAMAGE 10.0

#endif
